#! /bin/sh
### BEGIN INIT INFO
# Provides:          pictureframe
# Required-Start:    \$remote_fs \$syslog
# Required-Stop:     \$remote_fs \$syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
    start)
        echo "Starting picture frame"
        /home/wall1/onedrive-pi-picture-frame/frame.sh &
    ;;
    stop)
        echo -n "Shutting down picture frame"
        for i in `ps aux | grep 'frame.sh' | grep -v grep | awk '{print $2}'`
        do
          kill -9 $i
        done
        killall -9 fbi
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0

